# YOLO Segment 训练配置
task: segment  # 指定任务类型为分割
mode: train
model: yolov8s-seg.pt  # 中等规模模型平衡精度和速度

# 数据配置
data:
  train: data/train/images  # 训练图片目录
  val: data/val/images     # 验证图片目录
  names:
    0: belt_broken         # 类别名称
  
# 训练参数
epochs: 100
batch: 16
imgsz: 640
patience: 20  # 早停耐心值

# 优化器配置
optimizer:
  lr0: 0.01    # 初始学习率
  lrf: 0.01    # 最终学习率
  momentum: 0.937
  weight_decay: 0.0005

# 数据增强
augment:
  hsv_h: 0.015  # 色调增强
  hsv_s: 0.7    # 饱和度增强
  hsv_v: 0.4    # 亮度增强
  translate: 0.1 # 平移
  scale: 0.5    # 缩放
  fliplr: 0.5   # 左右翻转
  mosaic: 1.0   # 马赛克增强
