version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      args:
        PYTHON_VERSION: "3.10"
    ports:
      - "38881:38881"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
      - ./alerts:/app/alerts
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build: ./frontend
    ports:
      - "38880:38880"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:38881

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data

volumes:
  postgres_data: 