"""Add settings table

Revision ID: 002
Revises: 001
Create Date: 2025-02-22 22:44:11.123456 

"""
from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_api_url', sa.String(length=200), nullable=True),
        sa.Column('external_api_token', sa.String(length=200), nullable=True),
        sa.Column('external_api_secret', sa.String(length=200), nullable=True),
        sa.Column('alert_retention_days', sa.Integer(), nullable=True),
        sa.Column('alert_image_quality', sa.Integer(), nullable=True),
        sa.Column('log_level', sa.String(length=20), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ### 